### ISSUE TITLE
Armbian NEO

### ISSUE THREAD

**Issue by GeoDirk** [bitbank2/SPI_LCD#2]
I'm not getting anywhere when trying to use this library on an Armbian mainline/ NanoPi NEO.   I uncomment the #define USE_NANOPI2 line and use the #define USE_GENERIC lines.  Do the 'make' and then the 'make -f make_sample' without any issues.  However, when I try to run the lcd sample, I'm getting:

root@connectbox:~/SPI_LCD# ./lcd
Error setting SPI mode
Error setting SPI speed
Failed to open the SPI bus
Problem initializing spilcd library

Any ideas of what is missing and how I can get this running?

**Comment by bitbank2** [comment]
You did it correctly. I'm not sure of the GPIO pinout on the NEO. Are you sure it's compatible with the NanoPi2? The error may be due to your selection of the SPI bus number. You need to look in /dev and see what SPI buses are available (e.g. /dev/spidev0.0). This would be passed as 0 to the spilcdInit() function.

**Comment by bitbank2** [comment]
I just ordered a NanoPi NEO. It should arrive Nov 13th. I'll add a pinout translation table to SPI_LCD when I get it.

**Comment by bitbank2** [comment]
I just added a pin lookup table for the NanoPI NEO. It works fine with my ILI9341 connected to it. Using Armbian 4.13.12, the SPI speed measures at 19FPS (reasonable).

**Comment by attilagyorffy** [comment]
@bitbank2 I've chosen `USE_GENERIC` and `USE_NANOPINEO` in `spi_cld.c`. When running the test makefile,  we are using the default `LIBS= -lspi_lcd -lpthread -lm` config.

Assuming the GPIO ports are connected just fine, where should I set the Reset and Data/Command pins? Are these mapped to `GPIO_IN` and `GPIO_OUT` in the `spi_cld.c`?

Can you post the NanoPi NEO config you tested this with? Our ILI9341 is a bit of a black box but I assume we should match your config.

Thanks in advance
