### ISSUE TITLE
pigpio.h ?

### ISSUE THREAD

**Issue by elraro** [bitbank2/SPI_LCD#3]
Hello. Where can i find this file?

**Comment by bitbank2** [comment]
PIGPIO is a library specific to the Raspberry Pi. It ships pre-installed on Raspbian (including the H file). You can clone the git repo from here, but it won't work on anything besides the Broadcom BCM28xx chips. https://github.com/joan2937/pigpio

**Comment by elraro** [comment]
Oh fuck. So how do you got 25-60 fps in Orange pi zero? https://www.youtube.com/watch?v=0ox6p5-im7c
