### ISSUE TITLE
Displaying the whole screen

### ISSUE THREAD

**Issue by dotmick** [bitbank2/SPI_LCD#5]
Hi @bitbank2!

Thanks a lot for your work on the library.

I am currently building a small project using a raspi zero with a ili9341 screen. I want to run RetroPie/Recalbox on it but with all my tests (default drivers + fbcp) there's a small lag I can't get rid off.

I'd like to try using your driver and see if I can get better results. Is that possible? How should I do that do have the entire screen running on tft using your driver?

Thanks in advance!

**Comment by bitbank2** [comment]
SPI_LCD is a simple library to draw directly on SPI connected displays. It doesn't mimic what fbtft does (virtual frame buffer driver). It provides a simple set of functions for drawing text and graphics. I also wrote a library called BB-CP which does try to imitate the functionality of fbtft+fbcp. Give it a try.

**Comment by dotmick** [comment]
Thanks @bitbank2, I'll have a look!
