### ISSUE TITLE
ST7735R in 128x128 support?

### ISSUE THREAD

**Issue by dglaude** [bitbank2/SPI_LCD#7]
I have a ST7725R TFT LCD from Adafruit ( https://www.adafruit.com/product/2088 ) but it is 128x128, not 128*160.

It is connected to a Raspberry Pi with the following https://www.adafruit.com/product/3356 on SPI0.

I tried to modify your code to change all the instance of 160 by 128, but could not make it work. Your demo code does display garbage of color, and and the end I can almost read "Big rotd".

Would you know the difference between this and your reference ST7725 128*160 screen?

PS: No big deal, I can drive it and copy from fb0 with code from https://github.com/adafruit/Pi_Eyes but I was trying to use SPI_LCD and BB-CP (I know, it is supposed to be for  ili9341 320x240 LCD). This might be silly on it's own since there might be no need for optimisation for such a small screen. Thanks anyway for all the code you are sharing, and the ultimate goal of 60fps for retrogaming on little screen.

**Comment by bitbank2** [comment]
I don't own one of those displays, so I can test it. Check the datasheet for the ST7725R and see if there are some command differences between that and the ST7735R that I support.
