### ISSUE TITLE
Arduino Sample 

### ISSUE THREAD

**Issue by Pconti31** [bitbank2/SPI_LCD#9]
Not sure anyone is interested but I modified existing main.c to run as a Arduino .ino program.
Called it SPI_Sample.ino.  It was tested on Arduino Due rev3 using AdaFruit's 2.8 tft with ILI9341 driver.
Only one mod to spi_lcd.cpp
changed line 187 from
` SPI.transferBytes(pBuf, ucRXBuf, iLen);`
To:
`SPI.transfer(pBuf, iLen);
`
all files in the attached zip file
[SPI_Sample.zip](https://github.com/bitbank2/SPI_LCD/files/2912294/SPI_Sample.zip)

**Comment by bitbank2** [comment]
I have a fix for that which I just checked in to my oled_96 repo. The SPI.transferBytes is for ESP32 while the SPI.transfer is for everything else. I just checked in a fix for this repo. Can you please merge with my latest code and do a pull request for your sample app and I'll add it.

Thanks
